# Generated by Django 5.0.1 on 2024-08-02 13:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Diabetes', 'Diabetes'), ('Blood_pressure', 'Bloodpressure'), ('Asthma', 'Asthma')], max_length=100)),
                ('category_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('file_type', models.CharField(max_length=100, null=True)),
                ('file_size', models.BigIntegerField(default=0, null=True)),
                ('user_id', models.CharField(max_length=12, null=True)),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('crc32', models.CharField(max_length=8, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='directory',
            new_name='file_type',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='name',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='crc32',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='location',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='user_id',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uploadhistory')),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
