# Generated by Django 5.0.1 on 2024-08-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_uploadhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='key',
            field=models.IntegerField(default=42),
        ),
    ]
